# Generated by Django 3.0.2 on 2020-07-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_published', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=50)),
            ],
        ),
    ]
