# Generated by Django 3.0.2 on 2020-07-07 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='App_second',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_published', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=50)),
            ],
        ),
    ]
